
export const LOCATIONS = [
  '연길 (延吉)', '룡정 (龙井)', '도문 (图们)', '훈춘 (珲春)', 
  '화룡 (和龙)', '안도 (안투)', '돈화 (둔화)', '왕청 (왕칭)', '연변전체 (延边全区)'
];

export const BANNED_WORDS = ['도박', '불법', '성인', '사기', '도착', '대출', '赌博', '非法', '成人', '欺诈', '贷款'];

export const CATEGORIES = {
  RECRUITMENT: [
    { kr: '음식·외식', cn: '餐饮·外卖' },
    { kr: '판매·서비스', cn: '销售·服务' },
    { kr: '숙박·관광', cn: '住宿·旅游' },
    { kr: '의료·요양', cn: '医疗·养老' },
    { kr: '생산·건설', cn: '生产·建设' },
    { kr: '기타', cn: '其他' }
  ],
  PARTTIME: [
    { kr: '서빙·주방', cn: '服务员·后厨' },
    { kr: '매장·계산', cn: '门店·收银' },
    { kr: '배달·심부름', cn: '配送·跑腿' },
    { kr: '기타', cn: '其他' }
  ],
  BUSINESS: [
    { kr: '음식점', cn: '餐饮' },
    { kr: '카페', cn: '咖啡' },
    { kr: '판매', cn: '零售' },
    { kr: '미용', cn: '美容美发' },
    { kr: '교육', cn: '教育' },
    { kr: '의료', cn: '医疗' },
    { kr: '여행', cn: '旅游' },
    { kr: '생활서비스', cn: '生活服务' },
    { kr: '기타', cn: '其他' }
  ],
  REAL_ESTATE: [
    { kr: '아파트', cn: '公寓' },
    { kr: '주택', cn: '住宅' },
    { kr: '상가', cn: '商铺' },
    { kr: '사무실', cn: '办公' },
    { kr: '룸쉐어', cn: '合租' },
    { kr: '기타', cn: '其他' }
  ],
  PROMO: [
    { kr: '이벤트/할인', cn: '活动优惠' },
    { kr: '오픈/신규', cn: '新店开业' },
    { kr: '모집/수강', cn: '招生招聘' },
    { kr: '공연/전시', cn: '演出展览' },
    { kr: '기타', cn: '其他' }
  ],
  COMMUNITY_PHOTO: [
    { kr: '풍경/거리', cn: '风景/街道' },
    { kr: '음식/맛집', cn: '美食/探店' },
    { kr: '일상/생활', cn: '日常/生活' },
    { kr: '기타', cn: '其他' }
  ],
  COMMUNITY_USED: [
    { kr: '가전/디지털', cn: '家电/数码' },
    { kr: '가구/인테리어', cn: '家具/家居' },
    { kr: '의류/잡화', cn: '服装/杂货' },
    { kr: '기타', cn: '其他' }
  ],
  PARTNERSHIP: [
    { kr: '동업자 모집', cn: '合伙人招募' },
    { kr: '사업 제휴', cn: '业务合作' },
    { kr: '투자 유치', cn: '融资招商' },
    { kr: '공급/유통', cn: '供应/流通' }
  ]
};

export const DEAL_TYPES = [
  { kr: '매매', cn: '出售' },
  { kr: '월세', cn: '月租' },
  { kr: '전세/장기', cn: '长租' },
  { kr: '단기', cn: '短租' }
];

export const TRANSLATIONS = {
  KR: {
    appTitle: '연길 생활 허브',
    home: '홈',
    recruitment: '구인',
    resume: '구직',
    parttime: '알바',
    business: '비즈니스',
    promo: '홍보/광고',
    realEstate: '부동산',
    communityPhoto: '사진 자랑',
    communityUsed: '중고 거래',
    partnership: '동업 & 제휴',
    postButton: '무료 등록',
    filterRegion: '지역',
    koreanRequired: '한국어 가능',
    dormitory: '숙식제공',
    searchPlaceholder: '가게, 매물, 일자리 검색...',
    noLoginInfo: '로그인 없이 10초 만에 연락처로 직접 연결!',
    phone: '전화문의',
    chat: '실시간 톡',
    submit: '무료 등록하기',
    cancel: '닫기',
    title: '제목',
    shopName: '업체명',
    address: '주소',
    openHours: '영업시간',
    tags: '키워드 (쉼표 구분)',
    description: '상세 내용',
    salary: '급여',
    price: '가격',
    area: '면적',
    floor: '층수',
    moveInDate: '입주 가능일',
    location: '지역',
    urgent: '급구/급매',
    premium: '추천',
    all: '전체',
    report: '신고',
    adLabel: 'AD',
    startDate: '시작일',
    endDate: '종료일',
    safetyNotice: '신고 누적 시 게시물이 즉시 차단됩니다.',
    blacklistManage: '블랙리스트',
    adPackage: '광고상품',
    overview: '현황',
    postManage: '게시물 관리',
    reportManage: '신고 관리',
    adManage: '광고 관리',
    userView: '사용자 보기',
    adminLogin: '관리자 로그인',
    username: 'ID',
    password: 'PW',
    login: '로그인',
    photos: '사진 (최대 3장)',
    like: '좋아요',
    dislike: '싫어요',
    comments: '댓글',
    nickname: '닉네임',
    commentPlaceholder: '댓글을 입력하세요...',
    postComment: '등록',
    noComments: '첫 댓글을 남겨보세요!',
    bannedWordError: '금칙어가 포함되어 있습니다.',
    blockedUserError: '차단된 사용자입니다.',
    pendingApproval: '승인 대기 중입니다.',
    approve: '승인',
    reject: '거절',
    partnershipInquiry: '제휴 문의',
    inquiryPlaceholder: '문의 내용을 입력하세요...',
    sendInquiry: '문의 전송',
    inquirySuccess: '문의가 전달되었습니다.',
    views: '조회수',
    setPremium: '프리미엄 설정',
    stats: '통계',
    activePremiumPosts: '프리미엄 활성 수'
  },
  CN: {
    appTitle: '延吉生活圈',
    home: '首页',
    recruitment: '招聘',
    resume: '求职',
    parttime: '兼职',
    business: '商家信息',
    promo: '推广/广告',
    realEstate: '房产交易',
    communityPhoto: '照片墙',
    communityUsed: '二手交易',
    partnership: '合作/合伙',
    postButton: '免费发布',
    filterRegion: '区域',
    koreanRequired: '韩语',
    dormitory: '包食宿',
    searchPlaceholder: '搜索店铺、房源、职位...',
    noLoginInfo: '无需登录, 10秒内通过联系方式 직접 연결!',
    phone: '电话咨询',
    chat: '在线聊',
    submit: '免费发布',
    cancel: '关闭',
    title: '标题',
    shopName: '店名',
    address: '地址',
    openHours: '营业时间',
    tags: '关键词 (逗号分隔)',
    description: '详细内容',
    salary: '薪资',
    price: '价格',
    area: '面积',
    floor: '楼层',
    moveInDate: '入住日期',
    location: '区域',
    urgent: '急用/急售',
    premium: '精品',
    all: '全部',
    report: '举报',
    adLabel: '广告',
    startDate: '开始日期',
    endDate: '结束日期',
    safetyNotice: '累计举报后, 帖子将被立即屏蔽。',
    blacklistManage: '黑名单',
    adPackage: '广告套餐',
    overview: '概览',
    postManage: '内容管理',
    reportManage: '举报管理',
    adManage: '广告管理',
    userView: '用户视角',
    adminLogin: '管理员登录',
    username: '账号',
    password: '密码',
    login: '登录',
    photos: '照片 (最多3张)',
    like: '点赞',
    dislike: '无感',
    comments: '评论',
    nickname: '昵称',
    commentPlaceholder: '请输入评论...',
    postComment: '发布',
    noComments: '快来发表第一条评论吧!',
    bannedWordError: '包含禁止使用的词汇。',
    blockedUserError: '用户已被封禁。',
    pendingApproval: '等待管理员审核。',
    approve: '通过',
    reject: '拒绝',
    partnershipInquiry: '商务咨询',
    inquiryPlaceholder: '请输入咨询内容...',
    sendInquiry: '发送咨询',
    inquirySuccess: '咨询已成功发送。',
    views: '浏览量',
    setPremium: '设为精品',
    stats: '统计',
    activePremiumPosts: '活跃精品数'
  }
};
